# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Programming Gem Cutting
author: André Fernandes
email: andrefernandes6@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "Simplicity is a great virtue but it requires hard work to achieve it and education to appreciate it." – Edsger W. Dijkstra
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://asfer.github.io" # the base hostname & protocol for your site
twitter_username:       asfer6
linkedin_username:      asfer
stackoverflow_username: asfer
github_username:        asfer

collections:
  patterns:
    output: true

# Build settings
markdown: kramdown
